spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
#              memory: 2000Mi
            limits:
              cpu: "1.0"
#              memory: 2000Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"tomcat":{"max-threads":4}}}'
          - name: AB_JMX_EXPORTER_CONFIG
            value: "prometheus.yml"