rules:
  - pattern: 'org.apache.camel<context=(.*), type=routes, name=\"(.*)\"><>(.+):'
    name: $3
    help: $3
    labels:
      route: $2
      context: $1
      type: 'route'
  - pattern: 'org.apache.camel<context=(.*), type=context, name=\"(.*)\"><>(.+):'
    name: $3
    help: $3
    labels:
      context: $1
      type: 'context'
  - pattern: 'org.apache.camel<context=(.*), type=processors, name=\"(.*)\"><>(.+):'
    name: $3
    help: $3
    labels:
      processor: $2
      context: $1
      type: 'processor'

